#!/bin/sh 

if [ $# -eq 0 ]
  then
    echo "format: $0 1.0"
    exit 1
fi
VNAME=v$1
mkdir $VNAME || { echo 'dirctory exists, exit...'; exit 1; }
cp ~/innotek/stm32/tmp/lzdog/MDK-ARM/lzdog/lzdog.hex $VNAME/lzdog-$1.hex
cp ~/innotek/stm32/tmp/lzdog/MDK-ARM/lzdog/upgrade.bin $VNAME/lzdog-$1.bin
#cp v0.5/lzboot-b1.hex $VNAME/
srec_cat v0.5/lzboot-b1.hex -Intel $VNAME/lzdog-$1.hex -Intel -o $VNAME/lz-all-$1.hex
cp ~/innotek/stm32/workspace/Android-ota/app/build/outputs/apk/debug/lzdog-debug.apk $VNAME/lzdog-$1.apk

if [ -d "factory" ]; then rm -Rf factory; fi
mkdir -p factory/DM/linux
cksum=`./crc $VNAME/lzdog-$1.bin`
cat <<EOF > factory/DM/linux/UpgradeDesc.json
{
        "specVersion": "1.0",
        "fileName": "lzdog-$1.bin",
        "packageType": "softwarePackage",
        "version": "$VNAME",
        "deviceType": "sensor",
        "manufacturerName": "innotek",
        "model": "lzdog",
        "protocolType":"CoAP",
        "description":"software package",
        "versionCheckCode":"$cksum",
        "date":"2021-01-10"
}
EOF
mkdir factory/linux
cp  $VNAME/lzdog-$1.bin factory/linux/
cd factory
zip -r $VNAME.zip DM linux
zip lz-ota-$1.zip $VNAME.zip
cp lz-ota-$1.zip ../$VNAME/
cd ..

